eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka


server:
  port: 8085
spring:
  application:
    name: school
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro-school
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  config:
    students-url: http://localhost:8085/api/v1/student

management:
  tracing:
    sampling:
      probability: 1.0